### ISSUE TITLE
Upload to the chromewebstore

### ISSUE THREAD

**Issue by kaushalyap** [theapache64/source-pilot#25]
**Is your feature request related to a problem? Please describe.**
Have to manually install the extension.

**Describe the solution you'd like**
Upload it to Chrome Web Store so we can install it from there.

**Comment by theapache64** [comment]
I've created the draft last November itself.
![image](https://user-images.githubusercontent.com/9678279/71672709-c87ced80-2d9c-11ea-8b81-f1d5f646145f.png)

As we didn't receive any funds, I couldn't signup for the chrome developer account. Maybe you can be a part of this project by donating :moneybag:  $5 :wink:

**Comment by theapache64** [comment]
Closing this issue for now. Feel free to reopen. :hand:

**Comment by theapache64** [comment]
![image](https://user-images.githubusercontent.com/9678279/74112002-17e5e300-4bbf-11ea-8642-ce2fac4b125d.png)

It's happening :grin:

**Comment by theapache64** [comment]
Live : https://chrome.google.com/webstore/detail/source-pilot/hhnadopkkigcmecllcifpbgadkeddkbn
